language: go

env:
 - GOOS=linux GOARCH=amd64
 - GOOS=linux GOARCH=386
 - GOOS=linux GOARCH=arm
 - GOOS=linux GOARCH=arm64

 - GOOS=windows GOARCH=amd64
 - GOOS=windows GOARCH=386

 - GOOS=darwin GOARCH=amd64
 - GOOS=darwin GOARCH=386

 - GOOS=freebsd GOARCH=amd64
 - GOOS=freebsd GOARCH=386

script:
 - go build -v
