language: go
go:
  - "1.10"

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck
  - go get github.com/fzipp/gocyclo
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - ./build.sh
  - go test -v ./...
  - go vet ./...
  - megacheck ./...
  - gocyclo -over 19 $GO_FILES
  - golint -set_exit_status $(go list ./...)
