language: go

env:
  global:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
go:
  - "1.12"

script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go test ./...
  - go vet .

cache:
  directories:
   - $HOME/gopath/pkg/mod
