version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/hbagdi/rand

    steps:
      - checkout
      - run: go get golang.org/x/lint/golint
      - run: go get github.com/fzipp/gocyclo
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure
      - run: ./build.sh
      - run: go test -v ./...
      - run: go vet ./...
      - run: golint -set_exit_status $(go list ./...)
