// Copyright © 2017 Harry Bagdi <harry.bagdi@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package cmd

import (
	"errors"
	"fmt"
	"strconv"

	"github.com/brianvoe/gofakeit"
	"github.com/spf13/cobra"
)

var rgb bool
var hex bool

// colorCmd represents the color command
var colorCmd = &cobra.Command{
	Use:   "color",
	Short: "Generate a random color",
	Long: `Generate a random color
Default colors will be english names of colors and shades.
Hex and RGB formatted colors can be generated by using the flags.
Hex format is "#4285f4".
RGB format is "rgb(66,133,244)".
	`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if hex && rgb {
			return errors.New("--hex and --rgb are exclusive")

		}
		for i := 0; i < count; i++ {
			if hex {
				fmt.Println(gofakeit.HexColor())
			} else if rgb {
				rgb := gofakeit.RGBColor()
				fmt.Println("rgb(" + strconv.Itoa(rgb[0]) + "," +
					strconv.Itoa(rgb[1]) + "," + strconv.Itoa(rgb[2]) + ")")
			} else {
				fmt.Println(gofakeit.Color())
			}
		}
		return nil
	},
}

func init() {
	colorCmd.Flags().BoolVar(&hex, "hex", false, "output a color in hex format '#4285f4'")
	colorCmd.Flags().BoolVar(&rgb, "rgb", false, "output a color in rgb format 'rgb(66,133,244)'")
	rootCmd.AddCommand(colorCmd)
}
